#!/usr/bin/env bash
# Syncs third-party packages listed in tool/gen_packages.yaml into gen/.
# gen/ is gitignored — run this after clone and before pub get.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MANIFEST="${ROOT}/tool/gen_packages.yaml"
GEN_DIR="${ROOT}/gen"

if [[ ! -f "${MANIFEST}" ]]; then
  echo "Missing manifest: ${MANIFEST}" >&2
  exit 1
fi

if ! command -v python3 >/dev/null 2>&1; then
  echo "python3 is required to parse ${MANIFEST}" >&2
  exit 1
fi

mkdir -p "${GEN_DIR}"

list_packages() {
  python3 - "${MANIFEST}" <<'PY'
import sys
from pathlib import Path

path = Path(sys.argv[1])
text = path.read_text(encoding="utf-8")

packages = {}
name = None

for raw in text.splitlines():
    line = raw.split("#", 1)[0].rstrip()
    if not line.strip():
        continue
    if line.startswith("packages:"):
        continue
    indent = len(line) - len(line.lstrip(" "))
    stripped = line.strip()
    if indent == 2 and stripped.endswith(":"):
        name = stripped[:-1].strip()
        packages[name] = {}
        continue
    if name is None or ":" not in stripped:
        continue
    key, value = stripped.split(":", 1)
    packages[name][key.strip()] = value.strip().strip("'\"")

if not packages:
    raise SystemExit("No packages listed in manifest")

for pkg_name, meta in packages.items():
    repo = meta.get("repo")
    ref = meta.get("ref")
    if not repo or not ref:
        raise SystemExit("Package %r needs repo and ref" % (pkg_name,))
    print("%s\t%s\t%s" % (pkg_name, repo, ref))
PY
}

sync_one() {
  local name="$1"
  local repo="$2"
  local ref="$3"
  local dest="${GEN_DIR}/${name}"

  echo "→ ${name} @ ${ref}"

  if [[ -d "${dest}/.git" ]]; then
    git -C "${dest}" remote set-url origin "${repo}"
    git -C "${dest}" fetch --depth 1 origin "${ref}"
    git -C "${dest}" checkout --force --detach "FETCH_HEAD"
    git -C "${dest}" clean -fdx
  else
    rm -rf "${dest}"
    git clone --filter=blob:none --no-checkout "${repo}" "${dest}"
    git -C "${dest}" fetch --depth 1 origin "${ref}"
    git -C "${dest}" checkout --force --detach "FETCH_HEAD"
  fi

  echo "  synced → gen/${name}"
}

synced=0
while IFS=$'\t' read -r name repo ref; do
  sync_one "${name}" "${repo}" "${ref}"
  synced=$((synced + 1))
done < <(list_packages)

if [[ "${synced}" -eq 0 ]]; then
  echo "No packages listed in ${MANIFEST}" >&2
  exit 1
fi

{
  echo "# Generated by tool/sync_gen.sh — do not commit"
  date -u +"# synced_at: %Y-%m-%dT%H:%M:%SZ"
  while IFS=$'\t' read -r name repo ref; do
    echo "${name}: ${ref}"
  done < <(list_packages)
} >"${GEN_DIR}/.sync_meta"

echo "Done. Vendored packages are under gen/ (gitignored)."

# Copy unpublished nocterm packages into committed lib/src/vendor/ for pub.dev.
bash "${ROOT}/tool/vendor_from_gen.sh"
